- id: check-git-config-email
  name: Check Git Config Email
  description: This hook checks to ensure the Git config email matches one of the specified domains.
  entry: check-git-config-email
  language: python
  pass_filenames: false
  always_run: true
